??

diff --git a/tests/test1/test b/tests/test1/test
--- a/tests/test1/test
+++ b/tests/test1/test
@@ -5,12 +5,13 @@ do
     echo "====== testing $arg ======"
     sh ./$arg.sh marks.txt "testfile_file has space in name.2041" > $arg.output
     # answer generation.
-    sh ./$arg.sh marks.txt "testfile_file has space in name.2041" > $arg.expected
+    #sh ./$arg.sh marks.txt "testfile_file has space in name.2041" > $arg.expected
 
-    if ! diff $arg.output $arg.expected > /dev/null
+    if ! diff $arg.output $arg.expected >/dev/null
     then
-        echo "== [ERROR] $arg.output and $arg.expected did not match. =="
+        echo "== [ERROR] $arg.output and $arg.expected did not match. See $arg.output for yours. =="
         exit
     fi
+    rm $arg.output
     echo "===== test $arg passed! ====="
 done
